### ISSUE TITLE
Investigate huge_pages in x86-64

### ISSUE THREAD

**Issue by MatiasVara** [MatiasVara/torokernel#125]

**Comment by MatiasVara** [comment]
![selection_023](https://user-images.githubusercontent.com/1560874/34110784-f8dddb6e-e407-11e7-8554-0248f8e4dc5a.png)

**Comment by MatiasVara** [comment]
![selection_024](https://user-images.githubusercontent.com/1560874/34118165-48a8e4de-e41e-11e7-8866-ed8df20b857c.png)

**Comment by MatiasVara** [comment]
The first 256 should be 512 and the total is 256 TByte

**Comment by MatiasVara** [comment]
![selection_024](https://user-images.githubusercontent.com/1560874/34166727-f259d6ca-e4df-11e7-94ec-88c17cd692de.png)

**Comment by MatiasVara** [comment]
![selection_024](https://user-images.githubusercontent.com/1560874/34166818-3f69fb70-e4e0-11e7-992d-65daa1fabe14.png)

**Comment by MatiasVara** [comment]
Currently, Toro uses 2MB pages.

**Comment by MatiasVara** [comment]
Based on discussion on Osdev forum, the use of 1GB pages may not have a big impact in the time the processor walks through the page directory.

**Comment by dimakuv** [comment]
@MatiasVara I am looking at the ToroKernel for my own education.

Could you give an explanation why you chose 2MiB pages instead of the classic 4KiB ones? Was it to have a simpler 3-level page table hierarchy (instead of 4 levels)? I see that you setup a very simple hierarchy in your bootloader: https://github.com/torokernel/torokernel/blob/master/boot/pvhbootloader.asm#L173-L211.

Also, you have a weird comment here: https://github.com/torokernel/torokernel/blob/master/boot/pvhbootloader.asm#L203

In reality, `128 == 0b10000000` (bit 7) which is a `PS bit: if set, the entry describes a LARGE_PAGE`. So the comment is misleading, unless I misunderstand something.

**Comment by MatiasVara** [comment]
Hello, 
> @MatiasVara I am looking at the ToroKernel for my own education.
> 
> Could you give an explanation why you chose 2MiB pages instead of the classic 4KiB ones? Was it to have a simpler 3-level page table hierarchy (instead of 4 levels)? I see that you setup a very simple hierarchy in your bootloader: https://github.com/torokernel/torokernel/blob/master/boot/pvhbootloader.asm#L173-L211.

Yes, it was. Also, in the beginning, I thought that with bigger pages I would have a smaller page directory and this would speed up the walk-through of the MMU but I was wrong. I never did a benchmark though.    

> 
> Also, you have a weird comment here: https://github.com/torokernel/torokernel/blob/master/boot/pvhbootloader.asm#L203
> 
> In reality, `128 == 0b10000000` (bit 7) which is a `PS bit: if set, the entry describes a LARGE_PAGE`. So the comment is misleading, unless I misunderstand something.

I think my comment refers to the use of PWT and PCD flags in the PDE which controls the cache-policy. Since both are zero, I remind myself that I am using write-back policy (Chapter 4.5 and 11.5.2).

**Comment by MatiasVara** [comment]
I am going to add some screenshots just to not forget. 
![image](https://user-images.githubusercontent.com/1560874/108131054-fe6c5680-70b0-11eb-84c7-f53e9a703e2c.png)
![image](https://user-images.githubusercontent.com/1560874/108131101-13e18080-70b1-11eb-9e38-4ee56d568c80.png)
![image](https://user-images.githubusercontent.com/1560874/108131108-16dc7100-70b1-11eb-8862-e51382da78a8.png)
