### ISSUE TITLE
cannot build under fpc 3.0.0 on Windows

### ISSUE THREAD

**Issue by blestan** [MatiasVara/torokernel#2]
rtl cannot be compiled with fpc 3.0.0

**Comment by MatiasVara** [comment]
I am using fpc 2.6.4 for the moment. I will work on this issue asap.

**Comment by MatiasVara** [comment]
I could compile toro with fpc 3.0.0. However, some examples stop to work. I am working on it.

**Comment by blestan** [comment]
can you commit changes in rtl to compile with 3.0?

**Comment by MatiasVara** [comment]
I will do it soon. I have still some example that are not working well. ToroHello works well.

**Comment by MatiasVara** [comment]
I just commited the changes to compile toro with fpc 3.0.0. I tested on Win 10. Please fell free to test and tell me if it works.

**Comment by MatiasVara** [comment]
I have some problems with latest fpc version.

**Comment by MatiasVara** [comment]
Hi, I checked with the latest version of fpc that comes with Lazarus 1.6.2 and it works well. I get many Warnings but it compiles.

**Comment by MatiasVara** [comment]
I will open a new issue for the work in linux
