### ISSUE TITLE
Custom usage of ToroKernel

### ISSUE THREAD

**Issue by markfirmware** [MatiasVara/torokernel#61]
Is there a means to specify the upper bounds of the memory which is available to the heap? I'd like to reserve say 1MB as an I/O region accessible to the qemu monitor. Thanks, Mark.

**Comment by MatiasVara** [comment]
Hi mark, I don't understand very well the question. There is no API to allocate memory in a given address. However you can define from which address your available memory start, i.e., heap start address. It is defined in Arch.pas:157. I hope this answer your question. In addition, you would like to set  up such a region as NO-IN-CACHE so you can use RemovePageCache(Add: Pointer) which is defined in Arch.pas:1333. 

Regards, Matias.

**Comment by markfirmware** [comment]
I forgot to mention that I'm working on some experiments for x86 support for [ultibo](http:ultibo.org) and I hope to get some insights from your project.
Regards, Mark

**Comment by MatiasVara** [comment]
Sounds good. I think the core of x86-64 supporting is in _boot.s_

**Comment by markfirmware** [comment]
What about adding the ultibo kernel image to the toro disk image as a a file, and having the toro program load the ultibo kernel from disk and then jumping to it? Toro would be like a pre-boot loader as far as ultibo is concerned.

This might not be the ultimate answer but t could be a good stepping stone. The first version of ultibo/x86-64 doesn't need any I/o, just memory shared with an external i/o processor.

**Comment by MatiasVara** [comment]
In that case I think you can just try by using the build of Toro. The builder will take either pecoff or elf and combines them with boot.o and then create a .img that you can boot The bootloader will create a flat memory space in long mode, wake up all the cores and then pass the control to the boot core.

**Comment by markfirmware** [comment]
I discovered some easily repaired compiler warnings e.g. File system.pas:765 unused SPath. Are you open to pull requests to repair compiler warnings? Regards, Mark

**Comment by MatiasVara** [comment]
Hi Mark, sure I am open. Fell free to submit it, I will review it and then merge if everything goes well. I did a [How to Contribute ](https://github.com/MatiasVara/torokernel/wiki/How-to-Contribute)if you want to read first.

**Comment by markfirmware** [comment]
Swell. I will your expectations and any non-compliance will be unintentional. Please reject my pr's until they are suitable.

**Comment by markfirmware** [comment]
Can the kernel.bin produced within the buildimg.pas unit be used in the qemu -kernel option? This might help me meet my most immediate milestone. Thanks, Mark.

**Comment by MatiasVara** [comment]
What is the qemu -kernel option expecting? What is the format of the kernel.bin?

**Comment by markfirmware** [comment]
-kernel and -append are the two options that ultibo uses. My understanding that ultibo kernel.bin was a simple memory image but reading below, it is stated as bzImage. Thanks.

QEMU Manual:
https://qemu.weilnetz.de/doc/qemu-doc.html#Linux_002fMultiboot-boot-specific

2.3.11 Linux/Multiboot boot specific

When using these options, you can use a given Linux or Multiboot kernel without installing it in the disk image. It can be useful for easier testing of various kernels.

-kernel bzImage
Use bzImage as kernel image. The kernel can be either a Linux kernel or in multiboot format.

-append cmdline
Use cmdline as kernel command line

**Comment by MatiasVara** [comment]
I am not sure. Kernel.bin is the image of the kernel in memory. So if you put his content from $400000 adress and then jump to main the kernel will start to run. However, it does not have the bootloader. So the machine would not be prepared as kernel expects so It will crash.
ToroOS was a multiboot kernel. The executable had the multiboot head. It could be worth to check that code.

**Comment by markfirmware** [comment]
Ok, I was looking for a definite no. I will give it a few tries. My goal is a toro kernel that writes to memory without the disk and network support, and to add that support back in afterwards. Mark.

**Comment by MatiasVara** [comment]
You mean that the goal is a bootloader that writes to memory. The current bootloader is based on INT13H to get the kernel. So it will end up reading from any disk used as boot.

**Comment by markfirmware** [comment]
If I include the key parts of boot.s (perhaps boot.s without its disk actions) as part of toro kernel start up then it might work?

**Comment by MatiasVara** [comment]
Does it work when you use a kernel.bin? I meat did you try to do a very simple kernel.bin that does a loop? From that point, you could start to port some stuff from boot.s to your kernel and I can help you with that.

**Comment by markfirmware** [comment]
Not yet. If I strip down ToroHello and modify buildimg.pas to retain the kernel.bin, and run the toro build process on that, is it plausible that that kernel.bin can be passed to qemu -kernel?

**Comment by MatiasVara** [comment]
No. I don't think that will work.

**Comment by MatiasVara** [comment]
What you can do is to modify buildimg.pas to generate a multiboot kernel.bin

**Comment by markfirmware** [comment]
Ok. I will look into the ultibo approach for generating kernel.bin and apply that to toro. This will take a few hours. Thank you for your help.

**Comment by markfirmware** [comment]
Ok I will work towards the multiboot format.

**Comment by MatiasVara** [comment]
If you explain me better what are you trying to do we could figure out a simpler way to do it.

**Comment by MatiasVara** [comment]
This can help you with multiboot format. 

https://github.com/MatiasVara/ToroOS/blob/master/usr/src/boot/head32.s

**Comment by markfirmware** [comment]
The pre-milestone is to have the simplest possible test case for ultibo/Intel/qemu. That would be to write a series of integers to memory and observe them with the qemu monitor. I already have an ultibo/arm/qemu that works as a test control. It allocates 1MB at 0x3f00000 which is why I needed to adjust the start of toro heap - so I can use the same testing to confirm toro as I do ultibo.

I have already tested toro with https://github.com/markfirmware/torokernel/tree/markfirmware toroqemushm.pas

Be aware I'm doing several things at once in that branch, including some automated testing using codefresh and circleci.

So I want to close the gap between toro and ultibo by eliminating the toro disk image boot.  Of course the other side is to add disk image boot to ultibo which will come afterwards.

**Comment by MatiasVara** [comment]
I see. If you sucess by generating a multiboot kernel.bin I will be glad to add such a source to buildimg.pas. This for sure will close the gap between toro and ultibo. I would still keep the image since it is for baremetal.

**Comment by markfirmware** [comment]
Very good. I will work on the multiboot kernel.bin in a fresh branch so that you can assist more easily. It will be a few hours before I have some preliminary results.

**Comment by markfirmware** [comment]
Update:
I have added a 64-bit multiboot header to a simple pascal program - see the build.log in the artifacts:
https://circleci.com/gh/markfirmware/torokernel/60#artifacts/containers/0

At the end of the log qemu would rather have a 32 bit file.
I looked at the qemu source https://github.com/qemu/qemu/blob/master/hw/i386/multiboot.c#L189-L196

The branch at line 189 is for a short multiboot header which yields the "please use 32 bits" error message at line 196. The branch at line 219 is for a longer header that contains addresses and does not have that error check. I am working on updating head64.s to include the addresses and with that, I hope it will load in qemu.

I might not get back to this until Monday. Mark.

**Comment by MatiasVara** [comment]
Well done, you should also change head64.s to use 64 bit registers, e.g,. esp -> rsp and soon on.

**Comment by markfirmware** [comment]
https://circleci.com/gh/markfirmware/torokernel/62#artifacts/containers/0

The multiboot header now has the load and entry addresses and qemu accepts the kernel. The program is in a loop incrementing one of the words in the header. The header is at 400140 and the counter at 400154.

However, I can't see it incrementing using the qemu monitor xp/20w 0x400140
It stays at 0. Cached? Write protected? Fooling myself?

Thanks.

**Comment by markfirmware** [comment]
gdb testelfprogram

or

for qemu monitor:
qemu-system-x86_64 -kernel testelfprogram -display none

**Comment by MatiasVara** [comment]
Hello, if I understand well the log, you added PASCALMAIN in the multiboot header so qemu is just jumping to PASCALMAIN, am I correct? This means that is not executing "_inicio:"  so the stack is not set up.

**Comment by markfirmware** [comment]
Oh, ok. That is right. Do you know how to modify inicio correctly? Then I just set the header to point to inicio.

**Comment by MatiasVara** [comment]
I don't understand why you need MULTIBOOT_HEADER_LOAD

**Comment by MatiasVara** [comment]
In any case you can try to replace "dd PASCALMAIN" to "dd _inicio" but I don't know if it is the correct approach. I don't understand this either:
```
dd MULTIBOOT_HEADER_LOAD
dd 0
dd 0
```

**Comment by markfirmware** [comment]
I got those lines from https://www.idontnix.net/tech/flatimg.html

I think qemu needs LOAD to place the kernel in memory. It reads the kernel file first looking for the header before loading into memory.

What I need next is the correct 64 bit code for inicio. Thanks, Mark.

**Comment by MatiasVara** [comment]
_inicio is doing well, it is the same code than _start but using 64 bits registers.

**Comment by markfirmware** [comment]
Ok then I will try it. Thanks.

FYI https://github.com/qemu/qemu/blob/master/hw/i386/multiboot.c#L243-L257
is where qemu uses the load address for copying n the kernel.

**Comment by MatiasVara** [comment]
OK, thanks. In addition, you are setting: 
`MULTIBOOT_HEADER_LOAD		equ	0x400000  `
So I think you have to config the linkfile to say that the baseaddress is $4000000, otherwise it will fail to get the symbols.

**Comment by markfirmware** [comment]
That alone does not work. I am going to put in some assembly statements that modify that counter as the last step before transferring to PASCALMAIN and make sure that works as expected. Thanks for your help, I'm done for today. Mark.

**Comment by markfirmware** [comment]
And the linkfile.

**Comment by markfirmware** [comment]
See build.log in Artifacts:
https://circleci.com/gh/markfirmware/torokernel/75#artifacts/containers/0

* using __executable_start from link file instead of coding 0x400000 in header
* disassembly
* patch out call to FPC_INITIALIZEUNITS
* use gdb to show incrementing counter
* the counter does increment as expected

So I had to patch out the units init call. Without the patch the program counter was erratic. Any ideas on what that problem might be? This is a regular fpc program, not yet toro.

Also, any idea where I can find the source to _startup? It seems to save info from the header.

Thanks, Mark

**Comment by markfirmware** [comment]
Now trying Linux/elf build of te counter example:
https://80-97650146-gh.circle-artifacts.com/0/artifacts/build.log
Branch toroelftest 

system.pas(4653,1) Fatal: Unknown compilerproc "fpc_setjmp".

**Comment by MatiasVara** [comment]
- Hello, regarding FPC_INITIALIZEUNITS I had also patched that procedure. You can check in Arch.pas, I completely forgot about that. If it is not patched I think it is crashing when this function is invoked. 
- In Linux I have the same issue compiling Toro. I think it is the lack of that procedure in system.pas. I am currently compiling Toro only in Windows and using wine in Linux.

**Comment by markfirmware** [comment]
* The regular fpc, non-toro case was to get a a baseline working with elf/multiboot. That works well enough with the patch so I'll leave that the way it is for now.
* I saw that you have other compilerproc's in your system.pas, e.g. fpc_shortstr_copy. I found an implementation of fpc_setjmp in
https://github.com/ultibohub/FPC/blob/master/source/rtl/x86_64/setjump.inc
(Ultibo fpc - came up first in GitHub search.)

Do you think I can copy that to your system.pas and proceed? I'd like to go as far as I can on native linux before jumping to wine. Mark.

**Comment by MatiasVara** [comment]
You can try. That function should not be used.

**Comment by markfirmware** [comment]
Ok, it compiles and now the linker is missing fpc_empty_intf fpc_doneexception and fpc_raise_nested (all upper case.) I will provide empty definitions and proceed.

**Comment by MatiasVara** [comment]
Sounds good, I will happy to add that changes in order to compile toro in linux native.

**Comment by markfirmware** [comment]
Compiles and links. However -g for debug causes 'cannot find system type FILEREC.

**Comment by MatiasVara** [comment]
I am facing the same issue on Windows. I am not sure what is the problem. It works in Lazarus if I try to recompile two times.

**Comment by MatiasVara** [comment]
It could be enough to define such a structure in system.pas

**Comment by markfirmware** [comment]
FILEREC = record end;
TEXTREC = record end;

It works!
https://circleci.com/gh/markfirmware/torokernel/87#artifacts/containers/0

I will start tidying up the test script. I will also tidy up the dockerfile that builds the fpc/qemu/etc environment.

Now moving back to ultibo - does this entry state bypass the mmu so that all cpu addresses are also physical addresses?

**Comment by MatiasVara** [comment]
Toro is compiling and booting correctly in Linux? Perfect I should bring such a changes so if you submitted a PR I will review it. 
What do you mean with entry state? I am not sure if you are using boot.s but if you are using it every core will share the same page directory in which a flat memory address is used.

**Comment by markfirmware** [comment]
Ok, that is what I want - but I forgot to link in boot.s. I will look at buildimg.pas to see how it receives/transfers control.

The only test I've done so far is just write to memory. I'll do ToroHello next.

**Comment by MatiasVara** [comment]
When using multiboot qemu already gives the processor to the kernel in protect mode. This means that not all the code in boot.s is needed.

**Comment by markfirmware** [comment]
Is tests/boot.o compiled from boot/x86_64.s?

**Comment by MatiasVara** [comment]
Yeap

**Comment by markfirmware** [comment]
I will proceed to add the memory and mode switching routines from x86_64.s to _inicio.

**Comment by MatiasVara** [comment]
Sounds good. Fell free to ask.

**Comment by markfirmware** [comment]
Pause... I see you use qemu defaults for -machine and -cpu.  The default machine is
* pc-i440fx-2.1        Standard PC (i440FX + PIIX, 1996) (default)

but I can't figure out what the default cpu model is. Do you know what it is? I've started to search the qemu source for that.

Secondly, the working test program that updates a counter in memory uses 64 bit instructions but uses none of the boot loader memory/mode actions. Does this make sense to you?

**Comment by MatiasVara** [comment]
1. Do you mean the architecture? It is x86-64. 
2. I am not sure what is the state of the cpu when qemu pass the control to the kernel. It could be possible that the cpu is already in long mode with a flat memory space. You can verify the value of cr0 to check that. In that case you would only minors changes like set up the interruptions. Also it could be worth to verify how much memory can be addressed.

**Comment by markfirmware** [comment]
1. Not the programming model but the retail model number. The choices are

x86           qemu64  QEMU Virtual CPU version 2.1.2                  
x86           phenom  AMD Phenom(tm) 9550 Quad-Core Processor         
x86         core2duo  Intel(R) Core(TM)2 Duo CPU     T7700  @ 2.40GHz 
x86            kvm64  Common KVM processor                            
x86           qemu32  QEMU Virtual CPU version 2.1.2                  
x86            kvm32  Common 32-bit KVM processor                     
x86          coreduo  Genuine Intel(R) CPU           T2600  @ 2.16GHz 
x86              486                                                  
x86          pentium                                                  
x86         pentium2                                                  
x86         pentium3                                                  
x86           athlon  QEMU Virtual CPU version 2.1.2                  
x86             n270  Intel(R) Atom(TM) CPU N270   @ 1.60GHz          
x86           Conroe  Intel Celeron_4x0 (Conroe/Merom Class Core 2)   
x86           Penryn  Intel Core 2 Duo P9xxx (Penryn Class Core 2)    
x86          Nehalem  Intel Core i7 9xx (Nehalem Class Core i7)       
x86         Westmere  Westmere E56xx/L56xx/X56xx (Nehalem-C)          
x86      SandyBridge  Intel Xeon E312xx (Sandy Bridge)                
x86          Haswell  Intel Core Processor (Haswell)                  
x86        Broadwell  Intel Core Processor (Broadwell)                
x86       Opteron_G1  AMD Opteron 240 (Gen 1 Class Opteron)           
x86       Opteron_G2  AMD Opteron 22xx (Gen 2 Class Opteron)          
x86       Opteron_G3  AMD Opteron 23xx (Gen 3 Class Opteron)          
x86       Opteron_G4  AMD Opteron 62xx class CPU                      
x86       Opteron_G5  AMD Opteron 63xx class CPU                      
x86             host  KVM processor with all supported host features (only available in KVM mode)

**Comment by markfirmware** [comment]
2. I will check cr0 and memory availability

**Comment by MatiasVara** [comment]
I am not sure. I was using always the default configuration. As far I can tell you the bootloader is also working on KVM.

**Comment by markfirmware** [comment]
I get these (and more similar) during my build and I see you also get them too. how can we fix them? I want to eliminate the warnings that come up in my multiboot builds.

https://github.com/MatiasVara/torokernel/blob/master/rtl/Process.pas#L202-L11

Process.pas(202,19) Warning: Use of +offset(%ebp) for parameters invalid here
Process.pas(204,19) Warning: Use of +offset(%ebp) for parameters invalid here
Process.pas(211,70) Warning: Local variable "errc_reg" does not seem to be initialized
Process.pas(234,19) Warning: Use of +offset(%ebp) for parameters invalid here
Process.pas(236,19) Warning: Use of +offset(%ebp) for parameters invalid here
Process.pas(243,70) Warning: Local variable "errc_reg" does not seem to be initialized
Process.pas(266,19) Warning: Use of +offset(%ebp) for parameters invalid here
Process.pas(268,19) Warning: Use of +offset(%ebp) for parameters invalid here
Process.pas(275,70) Warning: Local variable "errc_reg" does not seem to be initialized
Process.pas(299,19) Warning: Use of +offset(%ebp) for parameters invalid here
Process.pas(301,19) Warning: Use of +offset(%ebp) for parameters invalid here
Process.pas(308,70) Warning: Local variable "errc_reg" does not seem to be initialized

**Comment by MatiasVara** [comment]
Hello,

The warning regarding the initialisation may be fixed by just initializing
the variables when they are defined in the stack. For the other warning, I
am not sure, we could move the content of rbp to a different register and
then used it instead rbp to point to memory.

On 25 Jul 2017 4:06 p.m., "markfirmware" <notifications@github.com> wrote:

I get these (and more similar) during my build and I see you also get them
too. how can we fix them? I want to eliminate the warnings that come up in
my multiboot builds.

https://github.com/MatiasVara/torokernel/blob/master/rtl/
Process.pas#L202-L11

Process.pas(202,19) Warning: Use of +offset(%ebp) for parameters invalid
here
Process.pas(204,19) Warning: Use of +offset(%ebp) for parameters invalid
here
Process.pas(211,70) Warning: Local variable "errc_reg" does not seem to be
initialized
Process.pas(234,19) Warning: Use of +offset(%ebp) for parameters invalid
here
Process.pas(236,19) Warning: Use of +offset(%ebp) for parameters invalid
here
Process.pas(243,70) Warning: Local variable "errc_reg" does not seem to be
initialized
Process.pas(266,19) Warning: Use of +offset(%ebp) for parameters invalid
here
Process.pas(268,19) Warning: Use of +offset(%ebp) for parameters invalid
here
Process.pas(275,70) Warning: Local variable "errc_reg" does not seem to be
initialized
Process.pas(299,19) Warning: Use of +offset(%ebp) for parameters invalid
here
Process.pas(301,19) Warning: Use of +offset(%ebp) for parameters invalid
here
Process.pas(308,70) Warning: Local variable "errc_reg" does not seem to be
initialized

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/MatiasVara/torokernel/issues/61#issuecomment-317767615>,
or mute the thread

**Comment by markfirmware** [comment]
Ok, I made a pr that repairs the warnings that are cluttering my current projects.

**Comment by MatiasVara** [comment]
Hi Mark, thank you very much for your contribution. I am currently out of
home so I will review when I come back.

**Comment by markfirmware** [comment]
When are you back? If not for a while I have some more warning reparations I can make.

**Comment by MatiasVara** [comment]
Hello,

I will be able from tonight.

**Comment by markfirmware** [comment]
Ok, I'm done updating the warnings pr

**Comment by MatiasVara** [comment]
Thanks Mark, I will review them this morning.

**Comment by markfirmware** [comment]
https://130-97650146-gh.circle-artifacts.com/0/artifacts/build.log

1. Some more warnings in Ext2 and IdeDisk and I'll be done with the first pass.
Did I miss any units? 
https://github.com/markfirmware/torokernel/blob/heavy/tests/toroelftest.pas#L1-L5

2. cr0 = 0x10, I printed results from Cupid calls with eax 0 and eax 1
https://en.m.wikipedia.org/wiki/CPUID

I can't find a definitive bit that indicates 64 bit long mode

The kernel uses addq but behaves like a 32-bit add. Does a 64-bit instruction on a 64-bit cpu behave like a 32-bit instruction when in real mode? It appears so

**Comment by MatiasVara** [comment]
Regarding with 2, check http://wiki.osdev.org/CPU_Registers_x86, it is not in protect mode yet. I think there is no bit to switch to long mode. It is a way to load the page directory whe you are in protect mode.

**Comment by markfirmware** [comment]
Thanks on 2. On 1 I need just a little help with
https://github.com/MatiasVara/torokernel/blob/master/rtl/drivers/IdeDisk.pas#L273
  {$IFDEF LINUX} mov rdx, IOPort {$ENDIF}
Warning: Size suffix and destination or source size do not match

I don't know how to eliminate the warning and preserve the intent. Thanks, Mark.

**Comment by MatiasVara** [comment]
You can replace by: 
mov edx, IOPort

**Comment by markfirmware** [comment]
Ok, final pr for warnings for this exercise are in. Now some lines from x86_64.s to get it into long mode, make sure memory paging and caching get set up, and this first milestone will be done. Thanks.

**Comment by MatiasVara** [comment]
Well done. I would like to integrate the use of a multiboot kernel in toro.
